version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5f:ca:3d:34:ff:30:1d:cb:ad:2f:e8:0d:e2:1a:3a:02"
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST
  # deployShinyio:
  #   docker:
  #     - image: bobfujp/shiny:57d0b256e9145a7a36e67ad0f932e3f059c3c19c
  #   steps:
  #     - checkout
  #     - run:
  #         name: deployToShinyIo
  #         command: |
  #           PWD=$(pwd)
  #           /usr/bin/R -e "rsconnect::setAccountInfo(name=\"infinityloop\", token=\"$R_TOKEN\", secret=\"$R_SECRET\"); setwd(\"$PWD\"); rsconnect::deployApp(forceUpdate=TRUE)"
  deploystg:
    docker:
      - image: boxboat/kubectl:1.15.12
    steps:
      - run: |
          export PWD=$(pwd)
          export K8S_DEPLOYMENT_NAME=`echo $CIRCLE_BRANCH | tr "[:upper:]" "[:lower:]"`
          echo $OKTETO_SECERT | base64 -d > "$PWD/config"
          wget -O ~/deployment.yaml "$STG_GIST_URL"
          sed -i -e "s/{{BRA_NAME}}/$K8S_DEPLOYMENT_NAME/; s/{{HASH_TAG}}/$CIRCLE_SHA1/; s/{{BRA_NAME_REAL}}/$CIRCLE_BRANCH/" ~/deployment.yaml
          kubectl --kubeconfig="$PWD/config" apply -f ~/deployment.yaml

workflows:
  version: 2
  chk-on-stg:
    jobs:
      - deploystg:
          filters:
            branches:
              only: /^de.*/
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
      # - deployShinyio:
      #     filters:
      #       branches:
      #         only: master
